import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, ExternalLink, GitBranch, Loader2, Network, ShieldCheck } from "lucide-react";
import React, { useMemo, useState } from "react";

type SavedArticle = { id: number; title: string; doi?: string | null; sourceUrl?: string | null };
type MapNode = { id: string; title?: string; year?: number | null; citationCount?: number | null; url?: string | null; type?: string };
type MapEdge = { source: string; target: string; relation?: string };

function statusCopy(status?: string) {
  if (status === "review_required") return { label: "requer revisão", className: "border-amber-300 bg-amber-50 text-amber-900" };
  if (status === "no_relation_reported") return { label: "sem relação reportada", className: "border-emerald-200 bg-emerald-50 text-emerald-800" };
  if (status === "not_checked") return { label: "sem DOI para consulta", className: "border-slate-200 bg-slate-50 text-slate-600" };
  return { label: "fonte indisponível", className: "border-slate-200 bg-slate-50 text-slate-600" };
}

export function CartographerEvidenceTools({ projectId, articles }: { projectId: number; articles: SavedArticle[] }) {
  const [selectedArticleId, setSelectedArticleId] = useState<number | null>(articles[0]?.id ?? null);
  const [checkEnabled, setCheckEnabled] = useState(false);
  const [mapEnabled, setMapEnabled] = useState(false);
  const [selectedNodeId, setSelectedNodeId] = useState<string | null>(null);
  const integrityInput = useMemo(() => ({ projectId, articleId: selectedArticleId ?? 0 }), [projectId, selectedArticleId]);
  const mapInput = useMemo(() => ({ projectId }), [projectId]);
  const integrity = trpc.cartographer.referenceIntegrity.useQuery(integrityInput, { enabled: checkEnabled && Boolean(selectedArticleId), retry: false });
  const citationMap = trpc.cartographer.citationMap.useQuery(mapInput, { enabled: mapEnabled, retry: false });
  const map = citationMap.data;
  const nodes = Array.isArray(map?.nodes) ? map.nodes as MapNode[] : [];
  const edges = Array.isArray(map?.edges) ? map.edges as MapEdge[] : [];
  const selectedNode = nodes.find(node => node.id === selectedNodeId) ?? null;
  const linkedEdges = selectedNode ? edges.filter(edge => edge.source === selectedNode.id || edge.target === selectedNode.id) : [];
  const integrityStatus = statusCopy(integrity.data?.status);

  return <section className="space-y-6" aria-label="Integridade editorial e mapa de citações">
    <div className="grid gap-px border border-slate-200 bg-slate-200 xl:grid-cols-2">
      <article className="bg-white p-5 md:p-6"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-amber-700" /><p className="text-[10px] font-bold tracking-[.16em] text-amber-700">INTEGRIDADE DE REFERÊNCIAS</p></div><h3 className="mt-3 font-reading text-xl font-black text-[#0A192F]">Sinal editorial conservador</h3><p className="mt-2 text-xs leading-5 text-slate-600">A consulta verifica relações editoriais expostas pela fonte pública. Um sinal requer conferência humana e não constitui acusação nem conclusão automática.</p></div></div>{articles.length ? <><div className="mt-5"><label htmlFor="integrity-article" className="text-xs font-bold text-slate-700">Referência do corpus</label><select id="integrity-article" value={selectedArticleId ?? ""} onChange={event => { setSelectedArticleId(Number(event.target.value)); setCheckEnabled(false); }} className="mt-2 h-10 w-full border border-slate-300 bg-white px-3 text-sm text-[#0A192F] focus:outline-none focus:ring-2 focus:ring-amber-400">{articles.map(article => <option key={article.id} value={article.id}>{article.title}</option>)}</select></div><Button type="button" onClick={() => setCheckEnabled(true)} disabled={integrity.isFetching} variant="outline" className="mt-4 rounded-none border-[#0A192F] text-[#0A192F] hover:bg-amber-50">{integrity.isFetching ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <AlertTriangle className="mr-2 h-4 w-4 text-amber-700" />}Consultar sinal editorial</Button>{integrity.data && <div className="mt-5 border-t border-slate-100 pt-4"><div className="flex flex-wrap items-center gap-2"><Badge variant="outline" className={`rounded-none ${integrityStatus.className}`}>{integrityStatus.label}</Badge><span className="text-[11px] text-slate-500">verificado em {new Date(integrity.data.checkedAt).toLocaleString("pt-BR")}</span></div><p className="mt-3 text-sm leading-6 text-slate-700">{integrity.data.detail}</p><p className="mt-2 text-[11px] text-slate-500">Fonte consultada: {integrity.data.source}</p></div>}{integrity.error && <p className="mt-4 text-xs leading-5 text-red-700">{integrity.error.message}</p>}</> : <p className="mt-6 border-l-2 border-amber-300 pl-3 text-sm leading-6 text-slate-600">Salve ao menos um estudo no corpus para verificar um sinal editorial.</p>}</article>
      <article className="bg-[#0A192F] p-5 text-white md:p-6"><div className="flex items-center gap-2"><Network className="h-4 w-4 text-amber-300" /><p className="text-[10px] font-bold tracking-[.16em] text-amber-300">REDE DE CITAÇÕES</p></div><h3 className="mt-3 font-reading text-xl font-black">Navegue pela vizinhança do corpus</h3><p className="mt-2 text-xs leading-5 text-slate-300">Expande referências e citações publicamente disponíveis para estudos salvos. A rede é limitada e pode ter cobertura parcial conforme a fonte.</p><Button type="button" onClick={() => setMapEnabled(true)} disabled={citationMap.isFetching || !articles.length} className="mt-5 rounded-none bg-amber-400 text-slate-950 hover:bg-amber-300">{citationMap.isFetching ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <GitBranch className="mr-2 h-4 w-4" />}Construir mapa navegável</Button>{citationMap.error && <p className="mt-4 text-xs leading-5 text-red-200">{citationMap.error.message}</p>}{map && <div className="mt-5 border-t border-white/15 pt-4"><div className="flex gap-5 text-xs"><span><strong className="text-amber-300">{nodes.length}</strong> nós</span><span><strong className="text-amber-300">{edges.length}</strong> relações</span></div>{Array.isArray(map.warnings) && map.warnings.length > 0 && <p className="mt-3 text-[11px] leading-5 text-slate-300">{map.warnings.join(" ")}</p>}</div>}</article>
    </div>
    {map && <article className="border border-slate-200 bg-white p-5 md:p-6"><div className="flex flex-col justify-between gap-3 border-b border-slate-100 pb-4 md:flex-row md:items-end"><div><p className="text-[10px] font-bold tracking-[.16em] text-amber-700">MAPA INTERATIVO</p><h3 className="mt-2 font-reading text-xl font-black text-[#0A192F]">Selecione um estudo para inspecionar suas relações</h3></div><p className="text-xs text-slate-500">Linhas representam referências ou citações encontradas.</p></div><div className="mt-5 grid gap-5 xl:grid-cols-[minmax(0,1fr)_300px]"><div className="grid gap-2 sm:grid-cols-2">{nodes.map(node => <button type="button" key={node.id} onClick={() => setSelectedNodeId(node.id)} className={`border p-3 text-left transition-colors ${selectedNodeId === node.id ? "border-amber-400 bg-amber-50" : "border-slate-200 bg-white hover:border-amber-300"}`}><div className="flex items-center justify-between gap-2"><Badge variant="outline" className="rounded-none border-slate-200 text-[10px] text-slate-500">{node.type ?? "estudo"}</Badge>{node.year && <span className="text-[11px] text-slate-500">{node.year}</span>}</div><p className="mt-3 line-clamp-3 text-sm font-bold leading-5 text-[#0A192F]">{node.title ?? node.id}</p>{typeof node.citationCount === "number" && <p className="mt-2 text-[11px] text-slate-500">{node.citationCount.toLocaleString("pt-BR")} citações</p>}</button>)}</div><aside className="border border-slate-200 bg-slate-50 p-4"><p className="text-xs font-bold uppercase tracking-[.14em] text-amber-800">Relações selecionadas</p>{selectedNode ? <><p className="mt-3 font-reading text-base font-bold text-[#0A192F]">{selectedNode.title ?? selectedNode.id}</p><p className="mt-4 text-xs leading-5 text-slate-600">{linkedEdges.length} relação(ões) no mapa atual.</p><div className="mt-3 space-y-2">{linkedEdges.map((edge, index) => <div key={`${edge.source}-${edge.target}-${index}`} className="border-l-2 border-amber-300 pl-3 text-xs text-slate-600"><strong>{edge.relation ?? "relação"}</strong>: {edge.source === selectedNode.id ? "cita ou referencia" : "é citado ou referenciado por"} {edge.source === selectedNode.id ? edge.target : edge.source}</div>)}</div>{selectedNode.url && <a href={selectedNode.url} target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center gap-1 text-xs font-bold text-amber-800">Abrir registro<ExternalLink className="h-3.5 w-3.5" /></a>}</> : <p className="mt-3 text-xs leading-5 text-slate-600">Escolha um nó para ver as relações disponíveis.</p>}</aside></div></article>}
  </section>;
}
